plugin:
  auto-update: true

server:
  chat-format:
    party: '&7[&6Party&7] &6{player}&7: &f{message}'
  locations:
    spawn: world:0.5:73.0:0.5:90.0:0.0
  essentials:
    emoji-feature: true

crafting-operations:
  blocked-items: [ ]

profanity-filter:
  add-default-words: true
  staff-notification-format: '&6[S] &f(&6Alley: &fProfanity Detected) &c{player}&f:
    &7{message}'
  filtered-words:
    - shit
    - fuck
    - bitch

commands:
  grant-cosmetic-permission: permission set {player} {permission}
  anti-syntax-message: '&cYou cannot execute {argument}.'

permissions:
  syntax-bypass-permission: alley.syntax.bypass

explosive:
  enabled: true
  values:
    fireball:
      explosion-range: 3.0
      vertical-kb: 2.2
      horizontal-kb: 2.5
      throw-speed: 0.7
    tnt:
      explosion-range: 3.0
      fuse-ticks: 60

game:
  blocked-commands:
    - kill
    - tp
  lives-per-game: 3
  portal-radius: 5
