plugin:
  # Whether to automatically update Alley Practice upon server start when a new version is available.
  auto-update: true

crafting-operations:
  blocked-items: []

commands:
  anti-syntax-message: '&cYou cannot execute {argument}.'
  # this command is executed whenever a player purchases a cosmetic item from the in game shop menu
  grant-cosmetic-permission: permission set {player} {permission}

configuration:
  arena-default-display-name:
    # When creating an arena, these are the default values that will be applied to it.
    ffa: '&6{arena-name}'
    shared: '&6{arena-name}'
    standalone: '&6{arena-name}'
  default-kit-values:
    # When creating a kit, these are the default values that will be applied to it.
    description: ''
    disclaimer: '&7{kit-name} kit disclaimer.'
    display-name: '&6{kit-name}'
    menu-title: '&6&l{kit-name}'

explosive:
  # Whether you want to use Alley's built-in explosive mechanics. (Fireball & Instant-TNT)
  enabled: true
  values:
    fireball:
      # The affected radius of the explosion measured in blocks.
      explosion-range: 3.0
      # The horizontal knockback multiplier applied to entities hit by the explosion.
      horizontal-kb: 2.5
      # The speed at which the fireball is thrown.
      throw-speed: 0.7
      # The vertical knockback multiplier applied to entities hit by the explosion.
      vertical-kb: 2.2
    tnt:
      # The affected radius of the explosion measured in blocks.
      explosion-range: 3.0
      # The fuse duration in ticks before the TNT explodes.
      fuse-ticks: 60

game:
  # The radius of the end portal thats going to act as the goal. (Better not change this unless you know what you're doing)
  portal-radius: 5
  # Blocked commands during matches
  blocked-commands:
    - kill
    - tp
  # the amount of lives each player will have (such as pearlfight)
  lives-per-game: 3

permissions:
  syntax-bypass-permission: alley.syntax.bypass
  color-code-usage-permission: alley.chat.color
  donators:
    # Allows players to select an arena in parties
    party-arena-selector: alley.donator.duel.arena.selector
    # Allows players to select an arena in /duel menu
    duel-arena-selector: alley.donator.duel.arena.selector
    # allow players to fly in the lobby / queue
    lobby-flight-bypass: alley.donator.lobby.flight
    # allow players to use emojis in chat (:sad:, etc)
    emoji-usage-permission: alley.donator.chat.emoji

profanity-filter:
  # Alley has a built in list of insults, if this is set to true, those will be used in addition to the custom list below
  add-default-words: true
  filtered-words:
    - shit
    - fuck
    - bitch
  staff-notification-format: '&6[S] &f(&6Alley: &fProfanity Detected) &c{player}&f: &7{message}'

server:
  chat-format:
    global:
      enabled: true
      format: '&7[{level}&7]&r {prefix}{rank-color}{name-color}{player}{suffix}{tag}{separator}{message}'
      separator: '&7: &f'
    tag-appearance:
      format: ' {tag-color}{tag-prefix}'
    party:
      format: '&7[&6Party&7] &6{player}&7: &f{message}'
  essentials:
    emoji-feature: true
  locations:
    spawn: world:10.0:100.0:100.0:0.0:0.0