command:
  anti-syntax-message: "&cYou cannot execute {argument}."
  # Allows you to execute for example alley:alley (syntax)
  syntax-bypass-perm: "alley.owner"
  # The dispatched/executed command by console when the players buys a cosmetic
  grant-cosmetic-permission-command: "permission set {player} {permission}"

spawn:
  # The spawn location of the server
  join-location: world:0.5:73.0:0.5:90.0:0.0

game:
  # In kits with lives setting enabled, this is the void (y) level where the player will die/lose a point.
  # [!] Must be within the cuboid of the arena.
  death-y-level: 10
  # The amount of lives each player will have in a lives match.
  lives: 3
  # The radius of the portal in blocks.
  portal-radius: 5

essentials:
  emojis: true # Whether to enable emojis in the chat or not (E. g. :smile:)
  chat-logging: # Setting to log the in-game chat to a specific discord channel via webhook (OPTIONAL)
    enabled: false
    webhook-url: "" # create a webhook on one of your channels and paste the url here, make sure the channel is accessible to the '@everyone' role, it won't work otherwise

parkour:
  starter-location: world:-5.1145064347201865:69.0:40.13243289901497:-1.9397448:20.588186

arena:
  # When creating an arena, the following displayname for each
  # arena type will be set. {arena} represents the arena name.
  default-display-name:
    shared: "&b{arena-name}"
    standalone: "&b{arena-name}"
    ffa: "&b{arena-name}"

kit:
  # The default name and description that's going to be set when creating a kit.
  default-name: "&b&l{kit-name}"
  default-description: "&7{kit-name} kit description."